'use client'
import { useMemo, useState } from 'react'
import { ClipboardList, FileSearch, GitCompareArrows, ShoppingCart, Receipt, Plus, CheckCircle2 } from 'lucide-react'
import Modal from '@/components/ui/modal/Modal'
import { createRfqAction, createSupplierQuoteAction, selectSupplierQuoteAction, createPurchaseOrderAction, createSupplierProformaAction } from '@/app/(dashboard)/achats/actions'

type Row=Record<string,unknown>
type Tab='rfq'|'quotes'|'compare'|'po'|'pi'
const money=(v:unknown,c:unknown)=>`${Number(v??0).toLocaleString('fr-FR',{maximumFractionDigits:2})} ${String(c??'USD')}`
const date=(v:unknown)=>v?new Intl.DateTimeFormat('fr-FR').format(new Date(String(v))):'—'
export default function ProcurementClient({suppliers,projects,rfqs,quotes,orders,proformas}:{suppliers:Row[];projects:Row[];rfqs:Row[];quotes:Row[];orders:Row[];proformas:Row[]}){
 const [tab,setTab]=useState<Tab>('rfq'); const [modal,setModal]=useState<Tab|null>(null)
 const sm=useMemo(()=>new Map(suppliers.map(x=>[String(x.id),String(x.company_name)])),[suppliers]); const pm=useMemo(()=>new Map(projects.map(x=>[String(x.id),`${x.reference} · ${x.name}`])),[projects])
 const tabs:[Tab,string,React.ElementType][]=[['rfq','RFQ',FileSearch],['quotes','Offres partenaires',ClipboardList],['compare','Comparaison',GitCompareArrows],['po','Purchase Orders',ShoppingCart],['pi','Proformas partenaires',Receipt]]
 const selected=quotes.filter(q=>q.status==='selectionnee')
 return <div className="max-w-7xl mx-auto space-y-4">
  <div className="page-header"><div><h1 className="page-title">Achats & Partenaires</h1><p className="page-subtitle">RFQ → offre partenaire → comparaison → sélection → Purchase Order → Proforma partenaire</p></div><button className="btn btn-primary btn-sm" onClick={()=>setModal(tab==='compare'?'quotes':tab)}><Plus className="w-3.5 h-3.5"/>Nouvelle opération</button></div>
  <div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['RFQ ouvertes',rfqs.filter(x=>!['cloturee','annulee'].includes(String(x.status))).length],['Offres reçues',quotes.length],['À comparer',quotes.filter(x=>['recue','en_analyse'].includes(String(x.status))).length],['PO ouverts',orders.filter(x=>!['cloture','annule'].includes(String(x.status))).length],['Proformas',proformas.length]].map(([l,v])=><div className="card p-4" key={String(l)}><div className="text-xs text-gray-400">{l}</div><div className="text-xl font-semibold text-navy-900 mt-1">{String(v)}</div></div>)}</div>
  <div className="border-b border-gray-200 overflow-x-auto"><div className="flex min-w-max">{tabs.map(([id,l,I])=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-3 text-xs font-medium border-b-2 flex gap-2 items-center ${tab===id?'border-gold-400 text-navy-900':'border-transparent text-gray-400'}`}><I className="w-3.5 h-3.5"/>{l}</button>)}</div></div>
  {tab==='rfq'&&<Table headers={['Référence','Partenaire','Projet / Affaire','Objet','Date limite','Statut']}>{rfqs.map(x=><tr key={String(x.id)}><Td strong>{x.reference}</Td><Td>{sm.get(String(x.supplier_id))}</Td><Td>{pm.get(String(x.project_id))??'—'}</Td><Td>{x.title}</Td><Td>{date(x.response_due_date)}</Td><Td><Badge>{x.status}</Badge></Td></tr>)}</Table>}
  {tab==='quotes'&&<Table headers={['Référence','Partenaire','Projet / Affaire','Montant','Délai','Garantie','Incoterm','Statut']}>{quotes.map(x=><tr key={String(x.id)}><Td strong>{x.supplier_reference||x.reference}</Td><Td>{sm.get(String(x.supplier_id))}</Td><Td>{pm.get(String(x.project_id))??'—'}</Td><Td strong>{money(x.amount,x.currency)}</Td><Td>{x.lead_time_days?`${x.lead_time_days} j`:'—'}</Td><Td>{x.warranty_months?`${x.warranty_months} mois`:'—'}</Td><Td>{x.incoterm}</Td><Td><Badge>{x.status}</Badge></Td></tr>)}</Table>}
  {tab==='compare'&&<Comparison quotes={quotes} sm={sm} pm={pm}/>} 
  {tab==='po'&&<Table headers={['PO','Partenaire','Projet / Affaire','Montant','Conditions','Livraison','Statut']}>{orders.map(x=><tr key={String(x.id)}><Td strong>{x.reference}</Td><Td>{sm.get(String(x.supplier_id))}</Td><Td>{pm.get(String(x.project_id))??'—'}</Td><Td strong>{money(x.amount,x.currency)}</Td><Td>{x.payment_terms}</Td><Td>{x.delivery_terms}</Td><Td><Badge>{x.status}</Badge></Td></tr>)}</Table>}
  {tab==='pi'&&<Table headers={['Référence','Partenaire','Projet / Affaire','Montant','Émission','Échéance','Statut']}>{proformas.map(x=><tr key={String(x.id)}><Td strong>{x.supplier_reference||x.reference}</Td><Td>{sm.get(String(x.supplier_id))}</Td><Td>{pm.get(String(x.project_id))??'—'}</Td><Td strong>{money(x.amount,x.currency)}</Td><Td>{date(x.issue_date)}</Td><Td>{date(x.due_date)}</Td><Td><Badge>{x.status}</Badge></Td></tr>)}</Table>}
  <Modal open={!!modal} onClose={()=>setModal(null)} title={modal==='rfq'?'Nouvelle RFQ':modal==='quotes'?'Enregistrer une offre partenaire':modal==='po'?'Créer un Purchase Order':'Enregistrer une Proforma partenaire'} size="lg"><div className="p-6">{modal==='rfq'?<RfqForm suppliers={suppliers} projects={projects}/>:modal==='quotes'?<QuoteForm suppliers={suppliers} projects={projects} rfqs={rfqs}/>:modal==='po'?<PoForm quotes={selected.length?selected:quotes} sm={sm}/>:modal==='pi'?<PiForm orders={orders} sm={sm}/>:null}</div></Modal>
 </div>
}
function Comparison({quotes,sm,pm}:{quotes:Row[];sm:Map<string,string>;pm:Map<string,string>}){return <div className="card p-5"><div className="mb-4"><h2 className="text-sm font-semibold text-navy-900">Comparaison des offres partenaires</h2><p className="text-xs text-gray-400 mt-1">La sélection doit précéder la création du PO. Comparez prix, délai, garantie et Incoterm — pas uniquement le prix.</p></div><Table headers={['Projet','Partenaire','Prix','Paiement','Délai','Garantie','Incoterm','Décision']}>{quotes.map(q=><tr key={String(q.id)}><Td>{pm.get(String(q.project_id))??'Sans projet'}</Td><Td strong>{sm.get(String(q.supplier_id))}</Td><Td strong>{money(q.amount,q.currency)}</Td><Td>{q.payment_terms}</Td><Td>{q.lead_time_days?`${q.lead_time_days} j`:'—'}</Td><Td>{q.warranty_months?`${q.warranty_months} mois`:'—'}</Td><Td>{q.incoterm}</Td><Td>{q.status==='selectionnee'?<span className="text-green-700 text-xs flex gap-1"><CheckCircle2 className="w-3.5 h-3.5"/>Sélectionnée</span>:<form action={selectSupplierQuoteAction}><input type="hidden" name="id" value={String(q.id)}/><button className="btn btn-outline btn-sm">Sélectionner</button></form>}</Td></tr>)}</Table></div>}
const input='input h-10 text-sm'; const label='text-xs font-medium text-gray-600 mb-1 block'
function SelectField({name,labelText,rows,required}:{name:string;labelText:string;rows:[string,string][];required?:boolean}){return <label><span className={label}>{labelText}</span><select name={name} required={required} className={input}><option value="">— Sélectionner —</option>{rows.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function RfqForm({suppliers,projects}:{suppliers:Row[];projects:Row[]}){return <form action={createRfqAction} className="space-y-4"><div className="grid md:grid-cols-2 gap-4"><SelectField name="supplier_id" labelText="Partenaire *" required rows={suppliers.map(x=>[String(x.id),String(x.company_name)])}/><SelectField name="project_id" labelText="Projet / Affaire" rows={projects.map(x=>[String(x.id),`${x.reference} · ${x.name}`])}/></div><label><span className={label}>Objet de la consultation *</span><input name="title" required className={input}/></label><label><span className={label}>Description / besoin</span><textarea name="description" className="input min-h-24 text-sm"/></label><div className="grid grid-cols-2 gap-4"><label><span className={label}>Devise</span><select name="currency" className={input}><option>USD</option><option>EUR</option><option>TRY</option></select></label><label><span className={label}>Réponse souhaitée avant</span><input type="date" name="response_due_date" className={input}/></label></div><Submit text="Créer et enregistrer la RFQ"/></form>}
function QuoteForm({suppliers,projects,rfqs}:{suppliers:Row[];projects:Row[];rfqs:Row[]}){return <form action={createSupplierQuoteAction} className="space-y-4"><div className="grid md:grid-cols-2 gap-4"><SelectField name="supplier_id" labelText="Partenaire *" required rows={suppliers.map(x=>[String(x.id),String(x.company_name)])}/><SelectField name="project_id" labelText="Projet / Affaire" rows={projects.map(x=>[String(x.id),`${x.reference} · ${x.name}`])}/></div><SelectField name="rfq_id" labelText="RFQ associée" rows={rfqs.map(x=>[String(x.id),`${x.reference} · ${x.title}`])}/><div className="grid md:grid-cols-3 gap-4"><Field name="supplier_reference" text="Référence fournisseur"/><Field name="amount" text="Montant *" type="number" required/><Field name="currency" text="Devise" value="USD"/></div><div className="grid md:grid-cols-3 gap-4"><Field name="lead_time_days" text="Délai (jours)" type="number"/><Field name="warranty_months" text="Garantie (mois)" type="number"/><Field name="incoterm" text="Incoterm"/></div><Field name="payment_terms" text="Conditions de paiement"/><Field name="validity_date" text="Validité de l’offre" type="date"/><Field name="notes" text="Notes / exclusions"/><Submit text="Enregistrer l’offre partenaire"/></form>}
function PoForm({quotes,sm}:{quotes:Row[];sm:Map<string,string>}){return <form action={createPurchaseOrderAction} className="space-y-4"><SelectField name="supplier_quotation_id" labelText="Offre partenaire retenue *" required rows={quotes.map(x=>[String(x.id),`${sm.get(String(x.supplier_id))} · ${x.supplier_reference||x.reference} · ${money(x.amount,x.currency)}`])}/><div className="rounded-lg bg-amber-50 border border-amber-200 p-3 text-xs text-amber-800">Le PO reprend le prix, la devise, le paiement, l’Incoterm et la garantie de l’offre sélectionnée. Les Purchase Terms V1 seront rattachées à l’étape contractuelle suivante.</div><Submit text="Créer le Purchase Order"/></form>}
function PiForm({orders,sm}:{orders:Row[];sm:Map<string,string>}){return <form action={createSupplierProformaAction} className="space-y-4"><SelectField name="purchase_order_id" labelText="Purchase Order *" required rows={orders.map(x=>[String(x.id),`${x.reference} · ${sm.get(String(x.supplier_id))} · ${money(x.amount,x.currency)}`])}/><div className="grid md:grid-cols-2 gap-4"><Field name="supplier_reference" text="N° Proforma fournisseur"/><Field name="amount" text="Montant (laisser vide = montant PO)" type="number"/></div><div className="grid md:grid-cols-2 gap-4"><Field name="issue_date" text="Date d’émission" type="date"/><Field name="due_date" text="Échéance" type="date"/></div><Submit text="Enregistrer la Proforma partenaire"/></form>}
function Field({name,text,type='text',required,value}:{name:string;text:string;type?:string;required?:boolean;value?:string}){return <label><span className={label}>{text}</span><input name={name} type={type} required={required} defaultValue={value} step={type==='number'?'0.01':undefined} className={input}/></label>}
function Submit({text}:{text:string}){return <div className="flex justify-end pt-3 border-t"><button className="btn btn-primary" type="submit">{text}</button></div>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="card p-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b">{headers.map(h=><th key={h} className="text-left text-xs font-medium text-gray-400 px-3 py-2 whitespace-nowrap">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{children}</tbody></table></div>}
function Td({children,strong}:{children:unknown;strong?:boolean}){return <td className={`px-3 py-3 text-xs ${strong?'font-semibold text-navy-900':'text-gray-600'}`}>{children == null || children === '' ? '—' : String(children)}</td>}
function Badge({children}:{children:unknown}){return <span className="inline-flex rounded-full bg-gray-100 px-2 py-1 text-2xs text-gray-600">{String(children ?? '—').replaceAll('_',' ')}</span>}
