'use client'

import { FormEvent, useEffect, useState } from 'react'
import { ArchiveRestore, ChevronLeft, ChevronRight, Inbox, Loader2, Mail, MailOpen, Menu, Paperclip, PenLine, RefreshCw, Reply, Search, Send, SendHorizontal, Star, Trash2, Unplug, X } from 'lucide-react'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'

type Folder = 'inbox'|'starred'|'sent'|'drafts'|'trash'
type Summary = { id:string; threadId:string; from:string; to:string; subject:string; date:string; snippet:string; unread:boolean; labels:string[] }
type Detail = { id:string; threadId:string; from:string; to:string; subject:string; date:string; messageId:string; references:string; body:string; labels:string[] }
type Attachment = { name:string; type:string; data:string }

const folders:Array<{id:Folder;label:string;icon:typeof Inbox}> = [
  {id:'inbox',label:'Boîte de réception',icon:Inbox},
  {id:'starred',label:'Messages suivis',icon:Star},
  {id:'sent',label:'Messages envoyés',icon:SendHorizontal},
  {id:'drafts',label:'Brouillons',icon:MailOpen},
  {id:'trash',label:'Corbeille',icon:Trash2},
]
const cleanName=(value:string)=>value.replace(/<[^>]+>/,'').replace(/^"|"$/g,'').trim()||value
const initials=(value:string)=>cleanName(value).split(/\s+/).slice(0,2).map(part=>part[0]?.toUpperCase()).join('')||'M'
function shortDate(value:string){const date=new Date(value);if(Number.isNaN(date.getTime()))return value;return date.toDateString()===new Date().toDateString()?date.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):date.toLocaleDateString('fr-FR',{day:'2-digit',month:'short'})}

export default function MailboxClient({connected,email,initialTo='',initialLeadId=''}:{connected:boolean;email?:string;initialTo?:string;initialLeadId?:string}){
  const [folder,setFolder]=useState<Folder>('inbox'),[messages,setMessages]=useState<Summary[]>([]),[selected,setSelected]=useState<Detail|null>(null)
  const [loading,setLoading]=useState(false),[compose,setCompose]=useState(Boolean(initialTo)),[mobileFolders,setMobileFolders]=useState(false)
  const [query,setQuery]=useState(''),[activeQuery,setActiveQuery]=useState(''),[nextToken,setNextToken]=useState(''),[tokens,setTokens]=useState(['']),[page,setPage]=useState(0)
  const [to,setTo]=useState(initialTo),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[attachments,setAttachments]=useState<Attachment[]>([])
  const folderLabel=folders.find(item=>item.id===folder)?.label

  async function load(token='',search=activeQuery){setLoading(true);const params=new URLSearchParams({folder});if(search)params.set('q',search);if(token)params.set('pageToken',token);const response=await fetch(`/api/email/messages?${params}`);const json=await response.json();setLoading(false);if(!response.ok)return toast.error(json.error);setMessages(json.messages??[]);setNextToken(json.nextPageToken??'')}
  useEffect(()=>{if(connected){setSelected(null);setTokens(['']);setPage(0);void load('',activeQuery)}} // eslint-disable-next-line react-hooks/exhaustive-deps
  ,[connected,folder])
  async function open(id:string){setLoading(true);const response=await fetch(`/api/email/messages?id=${encodeURIComponent(id)}`);const json=await response.json();setLoading(false);if(!response.ok)return toast.error(json.error);setSelected(json);setMessages(items=>items.map(item=>item.id===id?{...item,unread:false}:item))}
  async function act(action:'trash'|'restore'|'star'|'unstar'|'unread') {if(!selected)return;const response=await fetch('/api/email/messages',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:selected.id,action})});const json=await response.json();if(!response.ok)return toast.error(json.error);if(action==='trash'||action==='restore'){setSelected(null);void load(tokens[page]);return}const add=action==='star'?'STARRED':action==='unread'?'UNREAD':'';const remove=action==='unstar'?'STARRED':'';setSelected(item=>item?{...item,labels:[...item.labels.filter(label=>label!==remove),...(add&&!item.labels.includes(add)?[add]:[])]}:item)}
  function fresh(){setSelected(null);setTo(initialTo);setSubject('');setBody('');setAttachments([]);setCompose(true)}
  function reply(){if(!selected)return;setTo(selected.from.match(/<([^>]+)>/)?.[1]??selected.from);setSubject(/^re:/i.test(selected.subject)?selected.subject:`Re: ${selected.subject}`);setBody(`\n\n--- Message précédent ---\n${selected.body}`);setCompose(true)}
  async function send(){if(!to.trim())return toast.error('Ajoutez un destinataire');setLoading(true);const response=await fetch('/api/email/messages',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({to,subject,body,attachments,threadId:selected?.threadId,inReplyTo:selected?.messageId,references:selected?.references,leadId:initialLeadId||undefined})});const json=await response.json();setLoading(false);if(!response.ok)return toast.error(json.error);toast.success('E-mail envoyé');setCompose(false);setBody('');setAttachments([]);if(folder==='sent')void load()}
  async function chooseFiles(files:FileList|null){if(!files)return;const picked=[...files].slice(0,5);if(picked.reduce((total,file)=>total+file.size,0)>10_000_000)return toast.error('Maximum 10 Mo');const encoded=await Promise.all(picked.map(file=>new Promise<Attachment>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,type:file.type,data:String(reader.result).split(',')[1]});reader.onerror=reject;reader.readAsDataURL(file)})));setAttachments(encoded)}
  async function disconnect(){if(!confirm('Déconnecter votre boîte Gmail du CRM ?'))return;await fetch('/api/email/messages',{method:'DELETE'});location.reload()}
  function search(event:FormEvent){event.preventDefault();setActiveQuery(query);setTokens(['']);setPage(0);setSelected(null);void load('',query)}

  if(!connected)return <div className="mx-auto max-w-xl rounded-2xl border bg-white p-8 text-center shadow-sm"><Mail className="mx-auto h-10 w-10 text-gold-500"/><h2 className="mt-4 text-xl font-bold text-navy-950">Connecter ma boîte professionnelle</h2><p className="mt-2 text-sm leading-6 text-slate-500">Chaque utilisateur connecte sa propre boîte Google Workspace. Le CRM ne stocke jamais votre mot de passe.</p><a href="/api/email/google/connect" className="btn btn-primary mt-6">Connecter avec Google</a></div>

  return <div className="relative flex h-[calc(100dvh-7.5rem)] min-h-[620px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <aside className={cn('absolute inset-y-0 left-0 z-30 w-64 border-r bg-white p-4 transition-transform lg:static lg:translate-x-0',mobileFolders?'translate-x-0':'-translate-x-full')}>
      <div className="mb-5 flex items-center justify-between px-1"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.18em] text-gold-600">Messagerie</p><p className="mt-1 truncate text-xs text-slate-500">{email}</p></div><button className="rounded-lg p-2 text-slate-400 lg:hidden" onClick={()=>setMobileFolders(false)}><X className="h-5 w-5"/></button></div>
      <button className="btn btn-primary mb-5 w-full justify-center" onClick={()=>{fresh();setMobileFolders(false)}}><PenLine className="h-4 w-4"/>Nouveau message</button>
      <nav className="space-y-1">{folders.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>{setFolder(item.id);setMobileFolders(false)}} className={cn('flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition',folder===item.id?'bg-navy-950 text-white shadow-sm':'text-slate-600 hover:bg-slate-100 hover:text-navy-950')}><Icon className={cn('h-4 w-4',folder===item.id?'text-gold-400':'text-slate-400')}/>{item.label}</button>})}</nav>
      <div className="absolute bottom-4 left-4 right-4 border-t pt-4"><button className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-xs text-slate-500 hover:bg-slate-50" onClick={disconnect}><Unplug className="h-4 w-4"/>Déconnecter Gmail</button></div>
    </aside>{mobileFolders&&<button aria-label="Fermer le menu" className="absolute inset-0 z-20 bg-navy-950/25 lg:hidden" onClick={()=>setMobileFolders(false)}/>} 

    <section className={cn('w-full shrink-0 border-r lg:w-[390px] xl:w-[430px]',selected&&'hidden lg:block')}>
      <header className="border-b p-4"><div className="flex items-center gap-3"><button className="rounded-lg border p-2 text-slate-500 lg:hidden" onClick={()=>setMobileFolders(true)}><Menu className="h-4 w-4"/></button><div className="min-w-0 flex-1"><h1 className="truncate text-base font-bold text-navy-950">{folderLabel}</h1><p className="text-xs text-slate-400">Page {page+1}</p></div><button title="Actualiser" className="rounded-lg border p-2 text-slate-500 hover:bg-slate-50" onClick={()=>void load(tokens[page])}><RefreshCw className={cn('h-4 w-4',loading&&'animate-spin')}/></button></div><form className="relative mt-3" onSubmit={search}><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={event=>setQuery(event.target.value)} className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-3 text-sm outline-none focus:border-gold-400 focus:bg-white" placeholder="Rechercher un e-mail"/></form></header>
      <div className="h-[calc(100%-9rem)] overflow-y-auto">{messages.map(message=>{const correspondent=folder==='sent'?message.to:message.from;return <button key={message.id} onClick={()=>void open(message.id)} className={cn('flex w-full gap-3 border-b border-slate-100 p-4 text-left transition hover:bg-slate-50',selected?.id===message.id&&'bg-gold-50/70',message.unread&&'bg-blue-50/40')}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-navy-950 text-xs font-bold text-white">{initials(correspondent)}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className={cn('flex-1 truncate text-sm text-navy-950',message.unread?'font-bold':'font-semibold')}>{cleanName(correspondent)}</span><span className="shrink-0 text-[11px] text-slate-400">{shortDate(message.date)}</span></span><span className={cn('mt-1 block truncate text-sm text-slate-700',message.unread&&'font-semibold')}>{message.subject||'(Sans objet)'}</span><span className="mt-1 block truncate text-xs text-slate-400">{message.snippet}</span></span>{message.labels?.includes('STARRED')&&<Star className="mt-7 h-3.5 w-3.5 shrink-0 fill-gold-400 text-gold-500"/>}</button>})}{!messages.length&&!loading&&<div className="flex h-64 flex-col items-center justify-center px-6 text-center"><Mail className="h-8 w-8 text-slate-300"/><p className="mt-3 text-sm font-medium text-slate-500">Aucun message</p><p className="mt-1 text-xs text-slate-400">Ce dossier est vide ou aucun résultat ne correspond.</p></div>}{loading&&!messages.length&&<div className="flex h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-gold-500"/></div>}</div>
      <footer className="flex h-14 items-center justify-between border-t px-4 text-xs text-slate-400"><span>{messages.length} message{messages.length>1?'s':''}</span><span className="flex gap-2"><button disabled={page===0} onClick={()=>{const index=page-1;setPage(index);setSelected(null);void load(tokens[index])}} className="rounded-lg border p-2 disabled:opacity-30"><ChevronLeft className="h-4 w-4"/></button><button disabled={!nextToken} onClick={()=>{const next=[...tokens.slice(0,page+1),nextToken];setTokens(next);setPage(page+1);setSelected(null);void load(nextToken)}} className="rounded-lg border p-2 disabled:opacity-30"><ChevronRight className="h-4 w-4"/></button></span></footer>
    </section>

    <main className={cn('min-w-0 flex-1',!selected&&'hidden lg:block')}>{selected?<div className="flex h-full flex-col"><header className="flex flex-wrap items-center gap-2 border-b p-4"><button className="mr-1 rounded-lg border p-2 text-slate-500 lg:hidden" onClick={()=>setSelected(null)}><ChevronLeft className="h-4 w-4"/></button><button className="btn btn-secondary" onClick={reply}><Reply className="h-4 w-4"/>Répondre</button><button title="Suivre" className="rounded-lg border p-2 text-slate-500" onClick={()=>void act(selected.labels?.includes('STARRED')?'unstar':'star')}><Star className={cn('h-4 w-4',selected.labels?.includes('STARRED')&&'fill-gold-400 text-gold-500')}/></button><button title="Marquer comme non lu" className="rounded-lg border p-2 text-slate-500" onClick={()=>void act('unread')}><Mail className="h-4 w-4"/></button><button title={folder==='trash'?'Restaurer':'Corbeille'} className="rounded-lg border p-2 text-slate-500" onClick={()=>void act(folder==='trash'?'restore':'trash')}>{folder==='trash'?<ArchiveRestore className="h-4 w-4"/>:<Trash2 className="h-4 w-4"/>}</button></header><article className="flex-1 overflow-y-auto p-5 sm:p-7"><h2 className="text-xl font-bold leading-snug text-navy-950">{selected.subject||'(Sans objet)'}</h2><div className="mt-5 flex gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-navy-950 text-xs font-bold text-white">{initials(selected.from)}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-navy-950">{cleanName(selected.from)}</p><p className="truncate text-xs text-slate-500">De : {selected.from}</p><p className="truncate text-xs text-slate-400">À : {selected.to}</p></div><time className="ml-auto shrink-0 text-xs text-slate-400">{shortDate(selected.date)}</time></div><div className="my-6 border-t"/><pre className="whitespace-pre-wrap break-words font-sans text-sm leading-7 text-slate-700">{selected.body||'Ce message ne contient aucun texte.'}</pre></article></div>:<div className="flex h-full flex-col items-center justify-center px-8 text-center"><span className="rounded-2xl bg-slate-100 p-5"><MailOpen className="h-9 w-9 text-slate-400"/></span><h2 className="mt-5 font-bold text-navy-950">Votre messagerie professionnelle</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">Sélectionnez un message pour le consulter, le suivre ou y répondre directement depuis le CRM.</p></div>}</main>

    {compose&&<div className="fixed inset-0 z-[90] flex items-end justify-end bg-navy-950/30 p-0 sm:p-6"><div className="flex max-h-[92dvh] w-full flex-col overflow-hidden rounded-t-2xl bg-white shadow-2xl sm:max-w-2xl sm:rounded-2xl"><header className="flex items-center justify-between bg-navy-950 px-5 py-4 text-white"><div><h2 className="font-bold">{selected?'Répondre':'Nouveau message'}</h2><p className="mt-0.5 text-xs text-white/55">Depuis {email}</p></div><button className="rounded-lg p-1.5 hover:bg-white/10" onClick={()=>setCompose(false)}><X className="h-5 w-5"/></button></header><div className="flex-1 space-y-3 overflow-y-auto p-5"><input className="input" placeholder="Destinataire" value={to} onChange={event=>setTo(event.target.value)}/><input className="input" placeholder="Objet" value={subject} onChange={event=>setSubject(event.target.value)}/><textarea className="input min-h-64 resize-y" placeholder="Rédigez votre message…" value={body} onChange={event=>setBody(event.target.value)}/>{attachments.length>0&&<div className="flex flex-wrap gap-2">{attachments.map((file,index)=><span key={`${file.name}-${index}`} className="flex items-center gap-1 rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600"><Paperclip className="h-3 w-3"/>{file.name}<button onClick={()=>setAttachments(items=>items.filter((_,i)=>i!==index))}><X className="h-3 w-3"/></button></span>)}</div>}</div><footer className="flex items-center justify-between border-t p-4"><label className="cursor-pointer rounded-lg border p-2.5 text-slate-500 hover:bg-slate-50"><Paperclip className="h-4 w-4"/><input type="file" multiple className="hidden" onChange={event=>void chooseFiles(event.target.files)}/></label><button disabled={loading} onClick={send} className="btn btn-primary"><Send className="h-4 w-4"/>{loading?'Envoi…':'Envoyer'}</button></footer></div></div>}
  </div>
}
